server:
  port: 8080

dubbo:
  application:
    name: mall-oss-service
    version: 1.0.0
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 6000
    version: 1.0.0
    check: true
    file: ./.dubbo/mall-oss-service_registry
  scan:
    base-packages: com.mall.oss
  consumer:
    timeout: 6000
    check: false
    version: 1.0.0
    filter: dubboLogFilter
spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 127.0.0.1:9300
      # 未使用到ES 关闭其持久化存储
      repositories:
        enabled: false
