server:
  port: 8181

dubbo:
  application:
    name: mall-customer
    version: 1.0.0
  protocol:
    port: 28032
    status: server
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 6000
    version: 1.0.0
    check: true
    file: ./.dubbo/mall_customer_registry
  scan:
    base-packages: com.mall.customer
  provider:
    filter: dubboLogFilter

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mall.customer.base
  typeEnumsPackage: com.mall.customer.base
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#spring:
#  # 数据源
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/luckwine-customer?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: root
#    # ·加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    logSlowSql: true
#    druid:
#      stat-view-servlet:
#        # 默认true 内置监控页面首页/druid/index.html
#        enabled: true
#        url-pattern: /druid/*
#        # 允许清空统计数据
#        reset-enable: true
#        login-username: root
#        login-password: Aa123456
#        # IP白名单 多个逗号分隔
#        allow:
#        # IP黑名单
#        deny:

spring:
  shardingsphere:
    sharding:
      tables:
        cust_info:
          logic-table: cust_info # 逻辑表
          actual-data-nodes: ds${0..1}.cust_info  #数据节点, 真实表
          table-strategy:  # 分表策略
            inline:
              sharding-column: login_account
              algorithm-expression: cust_info
          database-strategy: # 分库策略
            inline:
              sharding-column: login_account
              algorithm-expression: ds${login_account % 2}
          key-generator:
            column: login_account
            type: SNOWFLAKE


      default-data-source-name: ds0
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/luckwine-customer-1
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/luckwine-customer-2
        username: root
        password: 123456